language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

#matrix:
#  include:
    #- php: 5.6
    #  env: SYMFONY_VERSION=2.8.*
    #- php: 7.0
    #  env: SYMFONY_VERSION=2.8.*
    #- php: 5.6
    #  env: SYMFONY_VERSION=3.0.*
    #- php: 7.0
    #  env: SYMFONY_VERSION=3.0.*

before_install:
  - phpenv config-add ./travis.php.ini
  - composer self-update

install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update $COMPOSER_FLAGS

script:
  - bin/phpunit --coverage-text
